# fly.toml app configuration file generated for frottage on 2025-05-12T09:57:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frottage'
primary_region = 'fra'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 256

[[mounts]]
source = 'data'                    # volume name
destination = '/data'
initial_size = "1GB"
auto_extend_size_threshold = 80
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "10GB"

[env]
DATABASE_PATH = "/data/database.db"
